### ISSUE TITLE
Unable to create topic

### ISSUE THREAD

**Issue by ranjeetranjan** [aleonsan/ansible-kafka#2]
bin/kafka-topics.sh --create --zookeeper 192.168.131.168:2181 --replication-factor 1 --partitions 1 --topic clicks_topic1
WARNING: Due to limitations in metric names, topics with a period ('.') or underscore ('_') could collide. To avoid issues it is best to use either, but not both.
Error while executing topic command : replication factor: 1 larger than available brokers: 0
[2017-03-11 10:11:39,649] ERROR org.apache.kafka.common.errors.InvalidReplicationFactorException: replication factor: 1 larger than available brokers: 0
 (kafka.admin.TopicCommand$)
[root@li819-138 kafka_2.12-0.10.2.0]# bin/kafka-topics.sh --create --zookeeper 192.168.131.168:2181 --replication-factor 1 --partitions 1 --topic clicks_topic1
Exception in thread "main" org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server '192.168.131.168:2181' with timeout of 30000 ms
	at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:1233)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:157)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:131)
	at kafka.utils.ZkUtils$.createZkClientAndConnection(ZkUtils.scala:79)
	at kafka.utils.ZkUtils$.apply(ZkUtils.scala:61)
	at kafka.admin.TopicCommand$.main(TopicCommand.scala:56)
	at kafka.admin.TopicCommand.main(TopicCommand.scala)

**Comment by ranjeetranjan** [comment]
bin/kafka-topics.sh --create --zookeeper 192.168.131.168:2181 --replication-factor 1 --partitions 1 --topic clicks_topic1
WARNING: Due to limitations in metric names, topics with a period ('.') or underscore ('_') could collide. To avoid issues it is best to use either, but not both.
Error while executing topic command : replication factor: 1 larger than available brokers: 0
[2017-03-11 10:26:07,662] ERROR org.apache.kafka.common.errors.InvalidReplicationFactorException: replication factor: 1 larger than available brokers: 0
 (kafka.admin.TopicCommand$)

**Comment by aleonsan** [comment]
Hello @ranjeetrajan

Try with:
bin/kafka-topics.sh --create --zookeeper 192.168.131.168:2181/kafka --replication-factor 1 --partitions 1 --topic clicks_topic1

as in kafka configuration file is set that is gonna subscribe to zookeeper under /kafka path.

Thanks for your comments.
